<a href="https://colab.research.google.com/github/DilushkumarVasu/NumPy/blob/main/FirstIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays vs Lists

In [ ]:
import numpy as np

In [ ]:
 L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for item in A:
  print(item)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
A + np.array([4,5])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
A * 2

array([2, 4, 6])

In [ ]:
L * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tan(A)

array([ 1.55740772, -2.18503986, -0.14254654])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# Dot Product

In [2]:
import numpy as np

In [3]:
a = np.array([1,2])
b = np.array([3,4])
test = zip(a,b)
print(list(test))

[(1, 3), (2, 4)]


In [4]:
dot = 0
for e,f in zip(a,b):
  dot += e * f
dot

11

In [5]:
dot = 0
for i in range(len(a)):
  dot += a[i]*b[i]
dot

11

In [6]:
a*b

array([3, 8])

In [7]:
np.sum(a*b)

11

In [8]:
(a*b).sum()

11

In [9]:
np.dot(a,b)

11

In [10]:
a.dot(b)

11

In [11]:
a @ b

11

In [13]:
amag = np.sqrt((a*a).sum())

In [14]:
amag

2.23606797749979

In [15]:
np.linalg.norm(a)

2.23606797749979

In [18]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [19]:
cosangle

0.9838699100999074

In [20]:
angle = np.arccos(cosangle)
angle

0.17985349979247847